package com.alura.conversor.comun.base;

import com.alura.conversor.entidad.Moneda;

import java.util.HashMap;
import java.util.Map;

public class CrearMonedas {

    public Map<String, Moneda> instanciarMonedas(){
        Map<String, Moneda> monedas = new HashMap<>();
        monedas.put("AED", new Moneda("Dirham de los Emiratos Árabes Unidos","AED",0.00090092));
        monedas.put("AFN", new Moneda("Afgani afgano","AFN",0.02112));
        monedas.put("ALL", new Moneda("Lek albanés","ALL",0.02248));
        monedas.put("AMD", new Moneda("Dram armenio","AMD",0.09450));
        monedas.put("ANG", new Moneda("Florín antillano neerlandés","ANG",0.00043912));
        monedas.put("AOA", new Moneda("Kwanza angoleño","AOA",0.2031));
        monedas.put("ARS", new Moneda("Peso argentino","ARS",0.06505));
        monedas.put("AUD", new Moneda("Dólar australiano","AUD",0.00036036));
        monedas.put("AWG", new Moneda("Florín arubeño","AWG",0.00043912));
        monedas.put("AZN", new Moneda("Manat azerí","AZN",0.00041865));
        monedas.put("BAM", new Moneda("Marco convertible de Bosnia y Herzegovina","BAM",0.00042766));
        monedas.put("BBD", new Moneda("Dólar de Barbados","BBD",0.00049063));
        monedas.put("BDT", new Moneda("Taka bangladesí","BDT",0.02672));
        monedas.put("BGN", new Moneda("Lev búlgaro","BGN",0.00042766));
        monedas.put("BHD", new Moneda("Dinar bahreiní","BHD",0.00009224));
        monedas.put("BIF", new Moneda("Franco burundés","BIF",0.6936));
        monedas.put("BMD", new Moneda("Dólar de Bermudas","BMD",0.00024532));
        monedas.put("BND", new Moneda("Dólar de Brunéi","BND",0.00032454));
        monedas.put("BOB", new Moneda("Boliviano boliviano","BOB",0.001697));
        monedas.put("BRL", new Moneda("Real brasileño","BRL",0.001178));
        monedas.put("BSD", new Moneda("Dólar bahameño","BSD",0.00024532));
        monedas.put("BTN", new Moneda("Ngultrum butanés","BTN",0.02016));
        monedas.put("BWP", new Moneda("Pula de Botsuana","BWP",0.003221));
        monedas.put("BYN", new Moneda("Rublo bielorruso","BYN",0.00062227));
        monedas.put("BZD", new Moneda("Dólar beliceño","BZD",0.00049063));
        monedas.put("CAD", new Moneda("Dólar canadiense","CAD",0.00032455));
        monedas.put("CDF", new Moneda("Franco congoleño","CDF",0.6091));
        monedas.put("CHF", new Moneda("Franco suizo","CHF",0.00021125));
        monedas.put("CLP", new Moneda("Peso chileno","CLP",0.2000));
        monedas.put("CNY", new Moneda("Yuan renminbi chino","CNY",0.001759));
        monedas.put("CRC", new Moneda("Colón costarricense","CRC",0.1330));
        monedas.put("CUP", new Moneda("Peso cubano","CUP",0.005888));
        monedas.put("CVE", new Moneda("Escudo de Cabo Verde","CVE",0.02411));
        monedas.put("CZK", new Moneda("Corona checa","CZK",0.005197));
        monedas.put("DJF", new Moneda("Franco de Yibuti","DJF",0.04360));
        monedas.put("DKK", new Moneda("Corona danesa","DKK",0.001631));
        monedas.put("DOP", new Moneda("Peso dominicano","DOP",0.01373));
        monedas.put("DZD", new Moneda("Dinar argelino","DZD",0.03300));
        monedas.put("EGP", new Moneda("Libra egipcia","EGP",0.007587));
        monedas.put("ERN", new Moneda("Nakfa eritreo","ERN",0.003680));
        monedas.put("ETB", new Moneda("Birr etíope","ETB",0.01347));
        monedas.put("EUR", new Moneda("Euro","EUR",0.00021866));
        monedas.put("FJD", new Moneda("Dólar fiyiano","FJD",0.00053803));
        monedas.put("FKP", new Moneda("Libra malvinense","FKP",0.00018765));
        monedas.put("FOK", new Moneda("Corona de las Islas Feroe","FOK",0.001631));
        monedas.put("GBP", new Moneda("Libra esterlina británica","GBP",0.00018765));
        monedas.put("GEL", new Moneda("Lari georgiano","GEL",0.00062851));
        monedas.put("GGP", new Moneda("Libra de Guernsey","GGP",0.00018765));
        monedas.put("GHS", new Moneda("Cedi ghanés","GHS",0.002766));
        monedas.put("GIP", new Moneda("Libra de Gibraltar","GIP",0.00018765));
        monedas.put("GMD", new Moneda("Dalasi gambiano","GMD",0.01466));
        monedas.put("GNF", new Moneda("Franco guineano","GNF",2.0820));
        monedas.put("GTQ", new Moneda("Quetzal guatemalteco","GTQ",0.001924));
        monedas.put("GYD", new Moneda("Dólar guyanés","GYD",0.05121));
        monedas.put("HKD", new Moneda("Dólar de Hong Kong","HKD",0.001918));
        monedas.put("HNL", new Moneda("Lempira hondureño","HNL",0.006036));
        monedas.put("HRK", new Moneda("Kuna croata","HRK",0.001647));
        monedas.put("HTG", new Moneda("Gourde haitiano","HTG",0.03401));
        monedas.put("HUF", new Moneda("Florín húngaro","HUF",0.08171));
        monedas.put("IDR", new Moneda("Rupia indonesia","IDR",3.7212));
        monedas.put("ILS", new Moneda("Nuevo shekel israelí","ILS",0.00089585));
        monedas.put("IMP", new Moneda("Libra de la Isla de Man","IMP",0.00018765));
        monedas.put("INR", new Moneda("Rupia india","INR",0.02016));
        monedas.put("IQD", new Moneda("Dinar iraquí","IQD",0.3202));
        monedas.put("IRR", new Moneda("Rial iraní","IRR",10.6833));
        monedas.put("ISK", new Moneda("Corona islandesa","ISK",0.03206));
        monedas.put("JEP", new Moneda("Libra de Jersey","JEP",0.00018765));
        monedas.put("JMD", new Moneda("Dólar jamaicano","JMD",0.03791));
        monedas.put("JOD", new Moneda("Dinar jordano","JOD",0.00017393));
        monedas.put("JPY", new Moneda("Yen japonés","JPY",0.03401));
        monedas.put("KES", new Moneda("Chelín keniano","KES",0.03473));
        monedas.put("KGS", new Moneda("Som kirguís","KGS",0.02151));
        monedas.put("KHR", new Moneda("Riel camboyano","KHR",1.0123));
        monedas.put("KID", new Moneda("Dólar de Kiribati","KID",0.00036036));
        monedas.put("KMF", new Moneda("Franco comorano","KMF",0.1076));
        monedas.put("KRW", new Moneda("Won surcoreano","KRW",0.3107));
        monedas.put("KWD", new Moneda("Dinar kuwaití","KWD",0.00007518));
        monedas.put("KYD", new Moneda("Dólar de las Islas Caimán","KYD",0.00020443));
        monedas.put("KZT", new Moneda("Tenge kazajo","KZT",0.1095));
        monedas.put("LAK", new Moneda("Kip laosiano","LAK",4.6883));
        monedas.put("LBP", new Moneda("Libra libanesa","LBP",3.6797));
        monedas.put("LKR", new Moneda("Rupia de Sri Lanka","LKR",0.07875));
        monedas.put("LRD", new Moneda("Dólar liberiano","LRD",0.04510));
        monedas.put("LSL", new Moneda("Loti lesothense","LSL",0.004441));
        monedas.put("LYD", new Moneda("Dinar libio","LYD",0.001163));
        monedas.put("MAD", new Moneda("Dírham marroquí","MAD",0.002381));
        monedas.put("MDL", new Moneda("Leu moldavo","MDL",0.004434));
        monedas.put("MGA", new Moneda("Ariary malgache","MGA",1.1023));
        monedas.put("MKD", new Moneda("Denar macedonio","MKD",0.01336));
        monedas.put("MMK", new Moneda("Kyat birmano","MMK",0.5148));
        monedas.put("MNT", new Moneda("Tugrik mongol","MNT",0.8419));
        monedas.put("MOP", new Moneda("Pataca de Macao","MOP",0.001975));
        monedas.put("MRU", new Moneda("Uquiya mauritana","MRU",0.008795));
        monedas.put("MUR", new Moneda("Rupia mauriciana","MUR",0.01111));
        monedas.put("MVR", new Moneda("Rufiyaa maldiva","MVR",0.003786));
        monedas.put("MWK", new Moneda("Kwacha malauí","MWK",0.2558));
        monedas.put("MXN", new Moneda("Peso mexicano","MXN",0.004115));
        monedas.put("MYR", new Moneda("Ringgit malayo","MYR",0.001117));
        monedas.put("MZN", new Moneda("Metical mozambiqueño","MZN",0.01562));
        monedas.put("NAD", new Moneda("Dólar namibio","NAD",0.004441));
        monedas.put("NGN", new Moneda("Naira nigeriano","NGN",0.1908));
        monedas.put("NIO", new Moneda("Córdoba nicaragüense","NIO",0.009002));
        monedas.put("NOK", new Moneda("Corona noruega","NOK",0.002464));
        monedas.put("NPR", new Moneda("Rupia nepalesa","NPR",0.03225));
        monedas.put("NZD", new Moneda("Dólar neozelandés","NZD",0.00038702));
        monedas.put("OMR", new Moneda("Rial omaní","OMR",0.00009432));
        monedas.put("PAB", new Moneda("Balboa panameño","PAB",0.00024532));
        monedas.put("PEN", new Moneda("Sol peruano","PEN",0.00087428));
        monedas.put("PGK", new Moneda("Kina de Papúa Nueva Guinea","PGK",0.00087703));
        monedas.put("PHP", new Moneda("Peso filipino","PHP",0.01336));
        monedas.put("PKR", new Moneda("Rupia pakistaní","PKR",0.06828));
        monedas.put("PLN", new Moneda("Złoty polaco","PLN",0.00097359));
        monedas.put("PYG", new Moneda("Guaraní paraguayo","PYG",1.7831));
        monedas.put("QAR", new Moneda("Rial qatarí","QAR",0.00089295));
        monedas.put("RON", new Moneda("Leu rumano","RON",0.001079));
        monedas.put("RSD", new Moneda("Dinar serbio","RSD",0.02562));
        monedas.put("RUB", new Moneda("Rublo ruso","RUB",0.02218));
        monedas.put("RWF", new Moneda("Franco ruandés","RWF",0.2859));
        monedas.put("SAR", new Moneda("Riyal saudí","SAR",0.00091993));
        monedas.put("SBD", new Moneda("Dólar de las Islas Salomón","SBD",0.002072));
        monedas.put("SCR", new Moneda("Rupia de Seychelles","SCR",0.003256));
        monedas.put("SDG", new Moneda("Libra sudanesa","SDG",0.1111));
        monedas.put("SEK", new Moneda("Corona sueca","SEK",0.002514));
        monedas.put("SGD", new Moneda("Dólar de Singapur","SGD",0.00032454));
        monedas.put("SHP", new Moneda("Libra de Santa Elena","SHP",0.00018765));
        monedas.put("SLE", new Moneda("Leona sierraleonesa","SLE",0.004709));
        monedas.put("SLL", new Moneda("Leona de Sierra Leona","SLL",4.7093));
        monedas.put("SOS", new Moneda("Chelín somalí","SOS",0.1395));
        monedas.put("SRD", new Moneda("Dólar de Surinam","SRD",0.009403));
        monedas.put("SSP", new Moneda("Libra sursudanesa","SSP",0.2352));
        monedas.put("STN", new Moneda("Dobra de Santo Tomé y Príncipe","STN",0.005357));
        monedas.put("SYP", new Moneda("Libra siria","SYP",0.6164));
        monedas.put("SZL", new Moneda("Lilangeni suazi","SZL",0.004441));
        monedas.put("THB", new Moneda("Baht tailandés","THB",0.008507));
        monedas.put("TJS", new Moneda("Somoni tayiko","TJS",0.002617));
        monedas.put("TMT", new Moneda("Manat turcomano","TMT",0.00083673));
        monedas.put("TND", new Moneda("Dinar tunecino","TND",0.00074502));
        monedas.put("TOP", new Moneda("Paʻanga tongano","TOP",0.00057327));
        monedas.put("TRY", new Moneda("Lira turca","TRY",0.006445));
        monedas.put("TTD", new Moneda("Dólar de Trinidad y Tobago","TTD",0.001665));
        monedas.put("TVD", new Moneda("Dólar tuvaluano","TVD",0.00036036));
        monedas.put("TWD", new Moneda("Nuevo dólar taiwanés","TWD",0.007620));
        monedas.put("TZS", new Moneda("Chelín tanzano","TZS",0.5993));
        monedas.put("UAH", new Moneda("Grivna ucraniana","UAH",0.009028));
        monedas.put("UGX", new Moneda("Chelín ugandés","UGX",0.9024));
        monedas.put("USD", new Moneda("Dólar estadounidense","USD",0.00024532));
        monedas.put("UYU", new Moneda("Peso uruguayo","UYU",0.009359));
        monedas.put("UZS", new Moneda("Som uzbeko","UZS",2.8793));
        monedas.put("VES", new Moneda("Bolívar venezolano","VES",0.007033));
        monedas.put("VND", new Moneda("Dong vietnamita","VND",5.8008));
        monedas.put("VUV", new Moneda("Vatu vanuatuense","VUV",0.02883));
        monedas.put("WST", new Moneda("Tala samoana","WST",0.00066279));
        monedas.put("XAF", new Moneda("Franco CFA de África Central","XAF",0.1434));
        monedas.put("XCD", new Moneda("Dólar del Caribe Oriental","XCD",0.00066235));
        monedas.put("XDR", new Moneda("Derechos especiales de giro","XDR",0.00018095));
        monedas.put("XOF", new Moneda("Franco CFA de África Occidental","XOF",0.1434));
        monedas.put("XPF", new Moneda("Franco CFP","XPF",0.02609));
        monedas.put("YER", new Moneda("Rial yemení","YER",0.06145));
        monedas.put("ZAR", new Moneda("Rand sudafricano","ZAR",0.004441));
        monedas.put("ZMW", new Moneda("Kwacha zambiano","ZMW",0.004655));
        monedas.put("ZWL", new Moneda("Dólar zimbabuense","ZWL",1.1945));

        return monedas;
    }
}
